?BANK 00

?INCLUDE 'cop_handlers_actors'
?INCLUDE 'cop_handlers_collision'
?INCLUDE 'cop_handlers_script'

---------------------------------------------

CopDispatch {
    REP #$20
    TXY 
    LDA $04, S
    STA $0C
    LDA $02, S
    DEC 
    STA $0A
    LDA [$0A]
    INC $0A
    AND #$00FF
    ASL 
    TAX 
    JMP ($&cop_dispatch_table, X)
}

cop_dispatch_table [
  &cop_handlers_collision.GenHdmaSine   ;00
  &cop_handlers_collision.QueueHdma   ;01
  &cop_handlers_collision.QueueDma   ;02
  &cop_handlers_collision.QueueHdmaChannel   ;03
  &cop_handlers_actors.StartMusic   ;04
  &cop_handlers_actors.FadeThenStartMusic   ;05
  &cop_handlers_actors.PlaySoundCh2   ;06
  &cop_handlers_actors.PlaySoundCh1   ;07
  &cop_handlers_actors.PlaySoundBoth   ;08
  &cop_handlers_actors.WriteApuIo1   ;09
  &cop_handlers_actors.WriteApuIo0   ;0A
  &cop_handlers_collision.MarkSolidHere   ;0B
  &cop_handlers_collision.ClearSolidHere   ;0C
  &cop_handlers_collision.MarkSolidOffset   ;0D
  &cop_handlers_collision.ClearSolidOffset   ;0E
  &cop_handlers_collision.MarkSolidAbs   ;0F
  &cop_handlers_collision.ClearSolidAbs   ;10
  &cop_handlers_collision.ClearCollisionHere   ;11
  &cop_handlers_collision.ClearTypeAbs   ;12
  &cop_handlers_collision.BranchIfSolidHere   ;13
  &cop_handlers_collision.BranchIfSolidOffset   ;14
  &cop_handlers_collision.BranchIfSolidNorth   ;15
  &cop_handlers_collision.BranchIfSolidSouth   ;16
  &cop_handlers_collision.BranchIfSolidWest   ;17
  &cop_handlers_collision.BranchIfSolidEast   ;18
  &cop_handlers_actors.MusicAndText   ;19
  &cop_handlers_collision.BranchIfTypeHere   ;1A
  &cop_handlers_collision.BranchIfTypeNorth   ;1B
  &cop_handlers_collision.BranchIfTypeSouth   ;1C
  &cop_handlers_collision.BranchIfTypeWest   ;1D
  &cop_handlers_collision.BranchIfTypeEast   ;1E
  &cop_handlers_collision.BranchIfNotOnGridline   ;1F
  &cop_handlers_collision.BranchIfActorNear   ;20
  &cop_handlers_collision.BranchIfPlayerNear   ;21
  &cop_handlers_collision.MoveToward   ;22
  &cop_handlers_collision.RngByte   ;23
  &cop_handlers_collision.RngMod   ;24
  &cop_handlers_collision.SetTilePos   ;25
  &cop_handlers_collision.QueueMapChange   ;26
  &cop_handlers_collision.WaitWhileOffscreen   ;27
  &cop_handlers_collision.BranchIfPlayerAt   ;28
  &cop_handlers_collision.BranchIfActorAt   ;29
  &cop_handlers_collision.BranchOnPlayerX   ;2A
  &cop_handlers_collision.BranchOnPlayerY   ;2B
  &cop_handlers_collision.BranchNearerAxis   ;2C
  &cop_handlers_collision.DirToPlayer   ;2D
  &cop_handlers_collision.DirToPlayerFrom   ;2E
  &cop_handlers_collision.BranchIfDirToPlayer   ;2F
  &cop_handlers_collision.BranchIfDirToPlayerFrom   ;30
  &cop_handlers_collision.BranchOnPlayerFacing   ;31
  &cop_handlers_actors.StageBgChange   ;32
  &cop_handlers_actors.ApplyBgChange   ;33
  &cop_handlers_actors.StageBgChangeFromDeathIdx   ;34
  &cop_handlers_collision.CardinalToPlayer   ;35
  &cop_handlers_actors.PaletteRestart   ;36
  &cop_handlers_actors.PaletteStart   ;37
  &cop_handlers_actors.PaletteStartLoop   ;38
  &cop_handlers_actors.PaletteStep   ;39
  &cop_handlers_actors.PaletteStepLoop   ;3A
  &cop_handlers_actors.SpawnThinkerParam   ;3B
  &cop_handlers_actors.SpawnThinker   ;3C
  &cop_handlers_actors.KillThinker   ;3D
  &cop_handlers_script.WaitForButton   ;3E
  &cop_handlers_script.WaitForRelease   ;3F
  &cop_handlers_script.BranchIfPressed   ;40
  &cop_handlers_script.BranchIfNotPressed   ;41
  &cop_handlers_collision.SetCollisionAbs   ;42
  &cop_handlers_collision.SnapToGrid   ;43
  &cop_handlers_actors.BranchIfPlayerInRelTiles   ;44
  &cop_handlers_actors.BranchIfPlayerInAbsTiles   ;45
  &cop_handlers_actors.CopyPosToPrev   ;46
  &cop_handlers_actors.CopyPosToNext   ;47
  &cop_handlers_actors.GetPlayerFacing   ;48
  &cop_handlers_actors.BranchIfBodyNe   ;49
  &cop_handlers_collision.ResumeAfterSnap   ;4A
  &cop_handlers_collision.DrawMetatileAbs   ;4B
  &cop_handlers_collision.DrawMetatileHere   ;4C
  &cop_handlers_collision.WorldMapStream3   ;4D
  &cop_handlers_collision.WorldMapStream4   ;4E
  &cop_handlers_collision.AdhocVramDma   ;4F
  &cop_handlers_collision.CopyPalette   ;50
  &cop_handlers_collision.Decompress   ;51
  &cop_handlers_collision.StageMove   ;52
  &cop_handlers_collision.TickMove   ;53
  &cop_handlers_collision.SetScratchPointer   ;54
  &cop_handlers_actors.ResetSpriteState   ;55
  &cop_handlers_actors.AdvanceSpriteAnim   ;56
  &cop_handlers_actors.SetDeathCallback   ;57
  &cop_handlers_actors.SetHitCallback   ;58
  &cop_handlers_actors.SetDodgeCallback   ;59
  &cop_handlers_actors.SetCollideCallback   ;5A
  &cop_handlers_actors.OrExtraFlags   ;5B
  &cop_handlers_actors.AndExtraFlags   ;5C
  &cop_handlers_collision.BranchIfBehindWall   ;5D
  &cop_handlers_actors.SetCustomCallback   ;5E
  &cop_handlers_collision.InitSineHdma   ;5F
  &cop_handlers_collision.TickSineHdma   ;60
  &cop_handlers_collision.BindSineHdma   ;61
  &cop_handlers_collision.BranchIfCollisionTypeNe   ;62
  &cop_handlers_collision.InitGravity   ;63
  &cop_handlers_collision.TickGravity   ;64
  &cop_handlers_script.StageWorldMapMove   ;65
  &cop_handlers_script.StageWorldMapChoice   ;66
  &cop_handlers_script.StageWorldMapMoveIds   ;67
  &cop_handlers_collision.BranchIfOffCamera   ;68
  &cop_handlers_collision.HaltIfMaxFrames   ;69
  &cop_handlers_actors.SetLinkedEntryPtr   ;6A
  &cop_handlers_script.PrintDialogStringAlt   ;6B
  &cop_handlers_collision.InitSpiral   ;6C
  &cop_handlers_collision.SpiralStep   ;6D
  #$0000   ;6E
  #$0000   ;6F
  #$0000   ;70
  #$0000   ;71
  #$0000   ;72
  #$0000   ;73
  #$0000   ;74
  #$0000   ;75
  #$0000   ;76
  #$0000   ;77
  #$0000   ;78
  #$0000   ;79
  #$0000   ;7A
  #$0000   ;7B
  #$0000   ;7C
  #$0000   ;7D
  #$0000   ;7E
  #$0000   ;7F
  &cop_handlers_actors.StageSpr   ;80
  &cop_handlers_actors.StageSprX   ;81
  &cop_handlers_actors.StageSprY   ;82
  &cop_handlers_actors.StageSprXY   ;83
  &cop_handlers_actors.StageSprLoop   ;84
  &cop_handlers_actors.StageSprLoopX   ;85
  &cop_handlers_actors.StageSprLoopY   ;86
  &cop_handlers_actors.StageSprLoopXY   ;87
  &cop_handlers_actors.SetMetasprite   ;88
  &cop_handlers_actors.AnimOnce   ;89
  &cop_handlers_actors.AnimLoop   ;8A
  &cop_handlers_actors.AnimOneFrame   ;8B
  &cop_handlers_actors.WaitForAnimFrame   ;8C
  &cop_handlers_actors.StageSprAndHitbox   ;8D
  &cop_handlers_actors.SetPlayerSpriteDirect   ;8E
  &cop_handlers_actors.StagePlayerSpr   ;8F
  &cop_handlers_actors.StagePlayerSprX   ;90
  &cop_handlers_actors.StagePlayerSprY   ;91
  &cop_handlers_actors.StagePlayerSprXY   ;92
  &cop_handlers_actors.RunPlayerAnim   ;93
  &cop_handlers_actors.StagePlayerSprWall   ;94
  &cop_handlers_actors.StagePlayerSprFromDP   ;95
  &cop_handlers_actors.WallAnimHere   ;96
  &cop_handlers_actors.WallAnimNorth   ;97
  &cop_handlers_actors.WallAnimSouth   ;98
  &cop_handlers_actors.SpawnBefore   ;99
  &cop_handlers_actors.SpawnBeforeFlags   ;9A
  &cop_handlers_actors.SpawnAfter   ;9B
  &cop_handlers_actors.SpawnAfterFlags   ;9C
  &cop_handlers_actors.SpawnAfterOffset   ;9D
  &cop_handlers_actors.SpawnAfterOffsetFlags   ;9E
  &cop_handlers_actors.SpawnAfterAbs   ;9F
  &cop_handlers_actors.SpawnAfterAbsFlags   ;A0
  &cop_handlers_actors.SpawnBeforeMarked   ;A1
  &cop_handlers_actors.SpawnAfterMarked   ;A2
  &cop_handlers_actors.SpawnAfterAbsMarked   ;A3
  &cop_handlers_actors.SpawnAfterOffsetMarked   ;A4
  &cop_handlers_actors.SpawnListAppend   ;A5
  &cop_handlers_actors.SpawnListAppendSpr   ;A6
  &cop_handlers_actors.MarkDeath   ;A7
  &cop_handlers_actors.KillPrev   ;A8
  &cop_handlers_actors.KillNext   ;A9
  &cop_handlers_actors.StageMoveX   ;AA
  &cop_handlers_actors.StageMoveY   ;AB
  &cop_handlers_actors.StageMoveXY   ;AC
  &cop_handlers_actors.ForceDirSW   ;AD
  &cop_handlers_actors.ForceDirNE   ;AE
  &cop_handlers_actors.ForceDirBoth   ;AF
  &cop_handlers_actors.ApplyMoveToChild   ;B0
  &cop_handlers_actors.ReloadMoveDurations   ;B1
  &cop_handlers_actors.SetPriorityMax   ;B2
  &cop_handlers_actors.SetPriorityMin   ;B3
  &cop_handlers_actors.ClearPriorityMax   ;B4
  &cop_handlers_actors.ClearPriorityMin   ;B5
  &cop_handlers_actors.SetOamPriority   ;B6
  &cop_handlers_actors.SetOamPalette   ;B7
  &cop_handlers_actors.ToggleHMirror   ;B8
  &cop_handlers_actors.ToggleVMirror   ;B9
  &cop_handlers_actors.ClearHMirror   ;BA
  &cop_handlers_actors.SetHMirror   ;BB
  &cop_handlers_actors.NudgePosition   ;BC
  &cop_handlers_script.RunBg3Script   ;BD
  &cop_handlers_script.DialogueOptions   ;BE
  &cop_handlers_script.PrintDialogString   ;BF
  &cop_handlers_script.SetInteractHandler   ;C0
  &cop_handlers_script.SetEntryHere   ;C1
  &cop_handlers_script.SetEntryHereAndYield   ;C2
  &cop_handlers_script.JumpAfterDelay   ;C3
  &cop_handlers_script.JumpNextFrame   ;C4
  &cop_handlers_script.RestoreSavedPtr   ;C5
  &cop_handlers_script.SetSavedPtr   ;C6
  &cop_handlers_script.JumpFar   ;C7
  &cop_handlers_script.CallNear   ;C8
  &cop_handlers_script.CallNearDeferred   ;C9
  &cop_handlers_script.LoopStart   ;CA
  &cop_handlers_script.LoopEnd   ;CB
  &cop_handlers_script.SetFlagByte   ;CC
  &cop_handlers_script.SetFlagWord   ;CD
  &cop_handlers_script.ClearFlagByte   ;CE
  &cop_handlers_script.ClearFlagWord   ;CF
  &cop_handlers_script.BranchOnFlagByte   ;D0
  &cop_handlers_script.BranchOnFlagWord   ;D1
  &cop_handlers_script.WaitOnFlagByte   ;D2
  &cop_handlers_script.WaitOnFlagWord   ;D3
  &cop_handlers_script.GiveItem   ;D4
  &cop_handlers_script.RemoveItem   ;D5
  &cop_handlers_script.BranchIfMissingItem   ;D6
  &cop_handlers_script.BranchIfItemEquipped   ;D7
  &cop_handlers_script.SetDungeonKillFlag   ;D8
  &cop_handlers_script.SwitchCase   ;D9
  &cop_handlers_script.WaitByte   ;DA
  &cop_handlers_script.WaitWord   ;DB
  &cop_handlers_collision.CameraPanDown   ;DC
  &cop_handlers_collision.CameraPanUp   ;DD
  &cop_handlers_collision.CameraPanRight   ;DE
  &cop_handlers_collision.CameraPanLeft   ;DF
  &cop_handlers_actors.Die   ;E0
  &cop_handlers_script.ReturnWithSignal   ;E1
  &cop_handlers_script.SetEntryFar   ;E2
]

cop_table_sentinel {
    NOP 
    BRA cop_table_sentinel
}